# Generated by Django 5.2.3 on 2025-06-12 10:04

import django.utils.timezone
import neworder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_ref_no', models.CharField(max_length=20, unique=True)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_type', models.CharField(choices=[('exchange', 'Exchange'), ('delivery', 'Delivery'), ('empty', 'Empty'), ('on-site tip', 'On-site Tip')], max_length=30)),
                ('name_or_company', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('expected_collection_date', models.DateField(default=neworder.models.get_default_date)),
                ('collection_date', models.DateField(blank=True, null=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('skip_size', models.CharField(choices=[('4', '4 Yard'), ('6', '6 Yard'), ('8', '8 Yard'), ('10', '10 Yard'), ('12', '12 Yard'), ('16', '16 Yard'), ('RORO', 'RORO'), ('Bin', 'Bin')], max_length=5)),
                ('quantity', models.PositiveIntegerField()),
                ('total_amount_with_vat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('account', 'Account'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('cash', 'Cash'), ('cheque', 'Cheque')], max_length=20)),
                ('inv_or_card_no', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('fulfillment_date', models.DateField(blank=True, null=True)),
                ('days_hired', models.PositiveIntegerField(blank=True, null=True)),
                ('extra_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exchange_delivery_ref_no', models.CharField(blank=True, max_length=100, null=True)),
                ('net_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('driver', models.CharField(blank=True, max_length=100, null=True)),
                ('skip_number', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sorted_date', models.DateField(blank=True, null=True)),
                ('extra_charge_waste', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
