# Generated by Django 5.2.3 on 2025-06-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neworder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neworder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('account', 'Account'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('cash', 'Cash'), ('cheque', 'Cheque')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='total_amount_with_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
